src/model/group/IGroup.java
package model.group;

import java.util.List;

import model.groupmembership.IGroupMembership;

import org.dsrg.soenea.domain.interf.IDomainObject;
import org.dsrg.soenea.domain.user.IUser;


public interface IGroup extends IDomainObject<Long> {
	public String getName();
	public void setName(String _name);
	public String getDesc();
	public void setDesc(String _desc);
	public List<IGroupMembership> getMembers();
	public void setMembers(List<IGroupMembership> _members);
	public boolean isMember(IUser user);
}

src/model/profile/IProfile.java
package model.profile;

import org.dsrg.soenea.domain.interf.IDomainObject;

public interface IProfile extends IDomainObject<Long> {
	public String getFirstName();
	public void setFirstName(String _firstname);
	public String getLastName();
	public void setLastName(String _lastname);
}

WebContent/WEB-INF/jsp/404.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>404 - Missing page</title>
</head>
<body>
	<h1>Henceforth shall be explained the meaning of life</h1>
	<p>Actually, nevermind.  Error 404.</p>
	<small>Please press the back button <sub><em>and never talk about this again</em></sub>.</small>
</body>
</html>

WebContent/WEB-INF/jsp/AdminView.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" 
	pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html lang='en'>
<head>
	<title>Groupr</title>
	<link rel="stylesheet" type="text/css" media="screen,print" href="/groupsoen3872011k/servlet/css/style.css" />
</head>
<body>
	<!-- content -->
	<div id='container'>
		<header>
			<div id='status'>
				<a href='#' id='viewProfile' class='TG' title='View your profile'><img src='/groupsoen3872011k/servlet/img/profile.png' alt='Profile' /></a>
				<a href='/groupsoen3872011k/servlet/' class='TG' title='Log out of Groupr'><img src='/groupsoen3872011k/servlet/img/logout.png' alt='Login' /></a>
			</div>
		
			<h1><a href='/groupsoen3872011k/servlet/home'>Groupr</a></h1>	
		</header>	

		<div class='sep'><noscript>Javascript is required to use GROUPR</noscript></div>

		<div id='gen'>
			
			
			<c:if test="${!empty success}">
				<div id='success'>${success}</div>
			</c:if>
			<c:if test="${!empty message}">
				<div id='error'>${message}</div>
			</c:if>

			<FORM  ENCTYPE="multipart/form-data" ACTION="/groupsoen3872011k/servlet/ImportCsv" METHOD=POST>
				<table>
		            <tr>
		            	<td colspan="2">
		            		<p align="center">
		                    <B>UPLOAD THE FILE</B>
		                    </p>
		            	</td>
		            </tr>
		            <tr>
		            	<td>
		            		<b>Choose the file To Upload:</b>
						</td>
		                <td>
		                	<INPUT NAME="file" TYPE="file">
		                </td>
		            </tr>
					<tr>
						<td colspan="2">
							<p align="right">
								<INPUT TYPE="submit"  VALUE="Send File" >
							</p>
						</td>
					</tr>
		        </table>
			</FORM>
		</div>
		
		
		<!-- Profile -->
		<div id='profileView'>
			<h3>Hey <em></em>${myUser.username}</em></h3>
			<p>Your info:</p>
			<table>
				<thead>
					<th>First name</th>
					<th>Last name</th>
					<th>Group</th>
				</thead>
				<tbody>
					<tr>
						<td>${myProfile.firstName}</td>
						<td>${myProfile.lastName}</td>
						<td>No group :(</td>
					</tr>
				</tbody>
			</table>
			
			<p>
				<a href="#" id="closeProfileView">Return</a>
			</p>
		</div>
		
		<footer>
			&copy; 2011 Shadi Isber, Nick Kilingi, Akmal Urazbaev
		</footer>
		
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
	<script src='/groupsoen3872011k/servlet/js/the.js' type='text/javascript'></script>	 
</BODY>
</HTML>

WebContent/WEB-INF/jsp/BrowseGroupsView.jsp
<%@page import="model.group.GroupProxy" %><%@page import="java.util.ArrayList" %><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>[
{"total":"${pageCount}"}<c:forEach items="${groups}" var="group" varStatus="loopCount"><c:choose><c:when test="${loopCount.count eq 1}">
,{
"name":"${group.name}",
"description":"${group.desc}",
"join":"<a class='joinRequest' href='/groupsoen3872011k/servlet/RequestEntry?groupID=${group.id}'>Join this group</a>"
}</c:when><c:otherwise>
,{
"name":"${group.name}",
"description":"${group.desc}",
"join":"<a class='joinRequest' href='/groupsoen3872011k/servlet/RequestEntry?groupID=${group.id}'>Join this group</a>"
}</c:otherwise></c:choose></c:forEach>
]

WebContent/WEB-INF/jsp/BrowseInvitesView.jsp
<%@page import="java.util.ArrayList" %><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>[
{"total":"${pageCount}"}<c:forEach items="${myInvites}" var="invite" varStatus="loopCount"><c:choose><c:when test="${loopCount.count eq 1}">
,{
"inviter":"${invite.inviter.username}",
"groupname":"${invite.group.name}",
"groupdesc":"${invite.group.desc}",
"accept":"<a href='/groupsoen3872011k/servlet/AcceptInvites?groupID=${invite.group.id}'><img width=30 height=30 src='/groupsoen3872011k/servlet/img/accept.png'/></a>",
"deny":"<a href='/groupsoen3872011k/servlet/DeclineInvites?inviteID=${invite.id}'><img width=30 height=30 src='/groupsoen3872011k/servlet/img/deny.png'/></a>"
}</c:when><c:otherwise>
,{
"inviter":"${invite.inviter.username}",
"groupname":"${invite.group.name}",
"groupdesc":"${invite.group.desc}",
"accept":"<a href='/groupsoen3872011k/servlet/AcceptInvites?groupID=${invite.group.id}'><img width=30 height=30 src='/groupsoen3872011k/servlet/img/accept.png' /></a>",
"deny":"<a href='/groupsoen3872011k/servlet/DeclineInvites?inviteID=${invite.id}'><img width=30 height=30 src='/groupsoen3872011k/servlet/img/deny.png' /></a>"
}</c:otherwise></c:choose></c:forEach> 
]

WebContent/WEB-INF/jsp/BrowseRequestsView.jsp
<%@page import="java.util.ArrayList" %><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>[
{"total":"${pageCount}"}<c:forEach items="${allGroupRequests}" var="aUser" varStatus="loopCount"><c:choose><c:when test="${loopCount.count eq 1}">
,{
"User":"${aUser.username}",
"Accept":"<a href='/groupsoen3872011k/servlet/AcceptEntry?requesterID=${aUser.id}'><img width=30 height=30 src='/groupsoen3872011k/servlet/img/accept.png'/></a>",
"Deny":"<a href='/groupsoen3872011k/servlet/CancelEntry?requesterID=${aUser.id}'><img width=30 height=30 src='/groupsoen3872011k/servlet/img/deny.png'/></a>"
}</c:when><c:otherwise>
,{
"User":"${aUser.username}",
"Accept":"<a href='/groupsoen3872011k/servlet/AcceptEntry?requesterID=${aUser.id}'><img width=30 height=30 src='/groupsoen3872011k/servlet/img/accept.png'/></a>",
"Deny":"<a href='/groupsoen3872011k/servlet/CancelEntry?requesterID=${aUser.id}'><img width=30 height=30 src='/groupsoen3872011k/servlet/img/deny.png'/></a>"
}</c:otherwise></c:choose></c:forEach>
]

WebContent/WEB-INF/jsp/MemberView.jsp
<%@page import="org.dsrg.soenea.domain.user.User" %>
<%@page import="java.util.List" %>
<%@ page language="java" contentType="text/html; charset=UTF-8" 
	pageEncoding="UTF-8" %>

<!DOCTYPE html>
<html lang='en'>
<head>
	<title>Groupr</title>
	<link rel="stylesheet" type="text/css" media="screen,print" href="/groupsoen3872011k/servlet/css/style.css" />
</head>
<body>
	<div id='overlay'>
		<div id='overlayBox'>
			<div id='closeOverlay'>
				<a href='#'>close</a>
			</div>
			<div id='sendInvite'>
				<h3>Invite members</h3>
				<form method='POST' action='/groupsoen3872011k/servlet/InviteMember'>
					<p>
						<label for='inviteeUsername'>Username</label>
							<input type='text' placeholder='e.g.: Ronald' name='inviteeUsername' />
					</p>
					<input type='hidden' name='groupName' value='${myGroup.name}' />
					<input type='submit' class='button' value='Send invite' />
				</form>
			</div>
			<div id='editGroupInfo'>
				<h3>Edit Group</h3>
				<form method='POST' action='/groupsoen3872011k/servlet/EditGroup'>
					<p>
						<label for='gName'>Group Name</label>
							<input type='text' value='${myGroup.name}' name='gName' />
					</p>
					<p>
						<label for='gDescr'>Group Description</label>
							<input type='text' value='${myGroup.desc}' name='gDescr' />
					</p>
					<input type='submit' class='button' value='Save edits' />
				</form>
			</div>
			 
		</div>
	</div>
	
	
	<div id='container'>
		<header>
			<div id='status'>
				<a href='#' id='viewProfile' class='TG' title='View your profile'><img src='/groupsoen3872011k/servlet/img/profile.png' alt='Profile' /></a>
				<a href='/groupsoen3872011k/servlet/' class='TG' title='Log out of Groupr'><img src='/groupsoen3872011k/servlet/img/logout.png' alt='Logout' /></a>
			</div>
		
			<h1><a href='/groupsoen3872011k/servlet/home'>Groupr</a></h1>	
		</header>	

		<div class='sep'>
			<noscript>Javascript is required to use GROUPR</noscript>
			<c:if test="${!empty success}">
				<div id='success'>${success}</div>
			</c:if>
			<c:if test="${!empty message}">
				<div id='error'>${message}</div>
			</c:if>
		</div>

		<div id='gen'>
			<nav>
				<a href='#' id='browseMyGroup' class='button'>
					<h3>Check Group</h3>
				</a>
				<a href='#' id='leaveGroup' class='button'>
					<h3>Browse Requests</h3>
				</a>
			</nav>
			
			<div class='clearfix'></div>
					
			<section id='content'>
				<div class='sep'></div>
				<div id='myGroupView'>
				
					<div id='myGroupInfo'>
						<h4>${myGroup.name}</h4>
						<div id='groupDescription'>${myGroup.desc}</div>					
						<div id='editGroupBtn'><a href='#'>edit group info</a></div>
					</div>
					
					<div class='clearfix'></div>
					<div class='subSep'></div>
					
					<div id='memberListFiller'>
						<img src='http://i.imgur.com/5wsH3.gif' width=30 height=30 alt='LOADING..' />
						<span>LOADING...</span>
					</div>

					<h4 class='center'>Missing a member? <a id='sendInviteBtn' href='#'>Send an invite!</a></h4>
				</div>
	
				<div id='leaveGroupView'>
					<h4>These people <em>really</em> want to be a part of your circle:</h4>
					
					<div id='groupRequestFiller'>
						<img src='http://i.imgur.com/5wsH3.gif' width=30 height=30 alt='LOADING..' />
						<span>LOADING...</span>
					</div>
				</div>
			</section>
		</div>
		
		<!-- Profile -->
		<div id='profileView'>
			<h3>Hey <em></em>${myUser.username}</em></h3>
			<p>Your info:</p>
			<table>
				<thead>
					<th>First name</th>
					<th>Last name</th>
					<th>Group</th>
				</thead>
				<tbody>
					<tr>
						<td>${myProfile.firstName}</td>
						<td>${myProfile.lastName}</td>
						<td>${myGroup.name}</td>
					</tr>
				</tbody>
			</table>

			<p>
				<a href="#" id="closeProfileView">Return</a>
			</p>
		</div>
		
		<footer>
			&copy; 2011 Shadi Isber, Nick Kilingi, Akmal Urazbaev
		</footer>
	</div>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
	<script src='/groupsoen3872011k/servlet/js/the.js' type='text/javascript'></script>	 
</body>
</html>

WebContent/WEB-INF/jsp/NonMemberView.jsp
<%@page import="org.dsrg.soenea.domain.user.User" %>
<%@page import="java.util.List" %>
<%@ page language="java" contentType="text/html; charset=UTF-8" 
	pageEncoding="UTF-8" %>

<!DOCTYPE html>
<html lang='en'>
<head>
	<title>Groupr</title>
	<link rel="stylesheet" type="text/css" media="screen,print" href="/groupsoen3872011k/servlet/css/style.css" />
</head>
<body>
	<!-- overlay -->
	<div id='overlay'>
		<div id='overlayBox'>
			<div id='closeOverlay'>
				<a href='#'>close</a>
			</div>
			<h3>Create a group</h3>
			<form method='POST' action='/groupsoen3872011k/servlet/CreateGroup'>
				<p>
					<label for='gName'>Name</label>
						<input type='text' placeholder='1337 Squad' name='gName' />
				</p>
				<p>
					<label for='gDescr'>Description</label>
						<input type='text' placeholder='The realest gangasters' name='gDescr' />
				</p>	
				<input type='hidden' name='username' value='${myUser.username}' />
				<input id='createGroupBtn' type='submit' class='button' value='Create my group' />
			</form>
		</div>
	</div>
	
	<!-- content -->
	<div id='container'>
		<header>
			<div id='status'>
				<a href='#' id='viewProfile' class='TG' title='View your profile'><img src='/groupsoen3872011k/servlet/img/profile.png' alt='Profile' /></a>
				<a href='/groupsoen3872011k/servlet/' class='TG' title='Log out of Groupr'><img src='/groupsoen3872011k/servlet/img/logout.png' alt='Login' /></a>
			</div>
		
			<h1><a href='/groupsoen3872011k/servlet/home'>Groupr</a></h1>	
		</header>	

		<div class='sep'>
			<noscript>Javascript is required to use GROUPR</noscript>
			<c:if test="${!empty success}">
				<div id='success'>${success}</div>
			</c:if>
			<c:if test="${!empty message}">
				<div id='error'>${message}</div>
			</c:if>
		</div>

		<div id='gen'>
			<nav>
				<a href='../BrowseGroups' id='browseGroups' class='button'>
					<h3>Browse Groups</h3>
				</a>
				<a href='../BrowseInvites' id='browseInvites' class='button'>
					<h3>Browse Invites</h3>
				</a>
			</nav>
			
			<div class='clearfix'></div>
					
			<section id='content'>
				<div class='sep'></div>
				
				<div id='groupView'>
					<div id='GroupViewFiller'>
						<img src='http://i.imgur.com/5wsH3.gif' width=30 height=30 alt='LOADING..' />
						<span>LOADING...</span>
					</div>
					
					<h4>Don't see your group? <a id='createGroup' href='#'>Why not create one?</a></h4>
				</div>
	
				<div id='inviteView'>
					<div id='InviteViewFiller'>
						<img src='http://i.imgur.com/5wsH3.gif' width=30 height=30 alt='LOADING..' />
						<span>LOADING...</span>
					</div>
				</div>
				
			</section>
		</div>
		
		<!-- Profile -->
		<div id='profileView'>
			<h3>Hey <em></em>${myUser.username}</em></h3>
			<p>Your info:</p>
			<table>
				<thead>
					<th>First name</th>
					<th>Last name</th>
					<th>Group</th>
				</thead>
				<tbody>
					<tr>
						<td>${myProfile.firstName}</td>
						<td>${myProfile.lastName}</td>
						<td>No group :(</td>
					</tr>
				</tbody>
			</table>
			
			<p>
				<a href="#" id="closeProfileView">Return</a>
			</p>
		</div>
		
		<footer>
			&copy; 2011 Shadi Isber, Nick Kilingi, Akmal Urazbaev
		</footer>
	</div>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
	<script src='/groupsoen3872011k/servlet/js/the.js' type='text/javascript'></script>	 
</body>
</html>

WebContent/WEB-INF/jsp/RequestEntryView.jsp
<%@page import="model.group.GroupProxy" %>
<%@page import="java.util.ArrayList" %>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:if test="${!empty success}">
		${success}
	</c:if>
	<c:if test="${!empty message}">
		${message}
</c:if>

WebContent/WEB-INF/jsp/ViewGroupView.jsp
<%@page import="java.util.ArrayList" %><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>[
{"total":"${pageCount}"}<c:forEach items="${myGroupMates}" var="memberProfile" varStatus="loopCount"><c:choose><c:when test="${loopCount.count eq 1}">
,{
"User":"${memberProfile.username}",
"Kick":"<a class='kick' href='/groupsoen3872011k/servlet/RemoveMember?memberID=${memberProfile.id}'><img src='/groupsoen3872011k/servlet/img/boot.png' width=30 height=30 alt='Kick this user' /></a>"
}</c:when><c:otherwise>
,{
"User list":"${memberProfile.username}",
"Kick":"<a class='kick' href='/groupsoen3872011k/servlet/RemoveMember?memberID=${memberProfile.id}'><img src='/groupsoen3872011k/servlet/img/boot.png' width=30 height=30 alt='Kick this user' /></a>"
}</c:otherwise></c:choose></c:forEach>
]